kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
priority: 3
metadata:
  name: logging-fluentd
  labels:
    name: logging-fluentd
    app.kubernetes.io/name: logging-fluentd
    app.kubernetes.io/component: fluentd
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: manually
allowPrivilegedContainer: false
allowHostDirVolumePlugin: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:logging-service:logging-fluentd
defaultAddCapabilities: []
requiredDropCapabilities: []
allowedCapabilities: []
volumes:
  - configMap
  - secret
  - hostPath
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
